# Generated by Django 3.2.5 on 2021-08-13 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('icon', models.FileField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_title', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='images/')),
                ('extra_images', models.ImageField(upload_to='images/')),
                ('gig_video', models.FileField(upload_to='images/')),
                ('description', models.TextField()),
                ('gig_rating', models.FloatField(default=0)),
                ('is_popular', models.BooleanField(default=False, null=True)),
                ('short_desc', models.TextField(null=True)),
                ('click', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='LandingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('sub_title', models.CharField(max_length=120)),
                ('sub_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.gig')),
                ('rate_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.rating')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_rqst_slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='files/')),
                ('budget', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.category')),
                ('delivery_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.deliverytime')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GigManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.gig')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.package')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='packages',
            field=models.ManyToManyField(through='mainApp.GigManager', to='mainApp.Package'),
        ),
        migrations.AddField(
            model_name='gig',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.services'),
        ),
        migrations.AddField(
            model_name='gig',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory'),
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='images/')),
                ('rating_text', models.CharField(max_length=1000, null=True)),
                ('level', models.IntegerField(default=None, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address1', models.CharField(max_length=210)),
                ('address2', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.gigmanager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
