# Generated by Django 3.2.5 on 2021-08-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='subcategory',
        ),
    ]
