# Generated by Django 3.2.6 on 2021-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_gig_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='pop_web',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
