# Generated by Django 3.2.6 on 2021-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_package_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=90)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
