# Generated by Django 3.2.6 on 2021-08-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rolemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostRequestModel',
        ),
    ]
