# Generated by Django 3.2.6 on 2021-08-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_delete_postrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postrequest_title', models.CharField(max_length=220)),
                ('attachment', models.FileField(upload_to='')),
                ('budget', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('deliver_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.deliverytime')),
            ],
        ),
    ]
