# Generated by Django 3.2.6 on 2021-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_buyerpostrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpostrequest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
