# Generated by Django 3.2.6 on 2021-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_buyerpostrequest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='address2',
        ),
        migrations.AlterField(
            model_name='buyerpostrequest',
            name='attachment',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
