# Generated by Django 3.2.6 on 2021-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210818_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
