# Generated by Django 3.2.6 on 2021-08-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_package_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_price',
        ),
    ]
