# Generated by Django 3.2.6 on 2021-08-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_checkout_grand_totla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='grand_totla',
            new_name='grand_total',
        ),
    ]
