# Generated by Django 3.2.6 on 2021-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_rename_grand_totla_checkout_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
