# Generated by Django 3.2.6 on 2021-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_checkout_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_iterested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
