# Generated by Django 3.2.6 on 2021-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_gigfavoritemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='cancellation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='impressions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='order_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='click',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
