# Generated by Django 3.2.6 on 2021-08-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0023_gig_gigs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigmanager',
            name='gig',
        ),
        migrations.RenameModel(
            old_name='GigFavoriteModel',
            new_name='OfferFavoriteModel',
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('offer_title', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='images/')),
                ('extra_images', models.ImageField(upload_to='images/')),
                ('offer_video', models.FileField(upload_to='images/')),
                ('description', models.TextField()),
                ('offer_rating', models.FloatField(default=0)),
                ('is_popular', models.BooleanField(default=False, null=True)),
                ('pop_web', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pro', models.BooleanField(default=False, null=True)),
                ('short_desc', models.TextField(null=True)),
                ('click', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('impressions', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cancellation', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('offer_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('REQUIRED MODIFICATION', 'REQUIRED MODIFICATION'), ('DRAFT', 'DRAFT'), ('DENIED', 'DENIED'), ('PAUSED', 'PAUSED')], default='ACTIVE', max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('packages', models.ManyToManyField(through='mainApp.GigManager', to='mainApp.Package')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gigmanager',
            name='Offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer'),
        ),
        migrations.AlterField(
            model_name='offerfavoritemodel',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer'),
        ),
        migrations.AlterField(
            model_name='reviewseller',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer'),
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
    ]
