# Generated by Django 3.2.6 on 2021-08-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_auto_20210821_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GigManager',
            new_name='OfferManager',
        ),
        migrations.RenameField(
            model_name='offerfavoritemodel',
            old_name='gig',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='reviewseller',
            old_name='gig',
            new_name='offer',
        ),
    ]
