# Generated by Django 3.2.6 on 2021-08-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20210821_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='rating_text',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
