# Generated by Django 3.2.6 on 2021-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20210823_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
