# Generated by Django 3.2.6 on 2021-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_auto_20210823_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubmit',
            name='file_field',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
