# Generated by Django 3.2.6 on 2021-08-24 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
