# Generated by Django 3.2.6 on 2021-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_auto_20210824_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
