# Generated by Django 3.2.6 on 2021-08-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_offer_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_complete',
        ),
    ]
