# Generated by Django 3.2.6 on 2021-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_remove_offer_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
