# Generated by Django 3.2.6 on 2021-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_alter_extendeduser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='level',
            field=models.CharField(blank=True, choices=[('NEW SELLER', 'NEW SELLER'), ('LEVEL1', 'LEVEL1'), ('LEVEL 2', 'LEVEL 2'), ('LEVEL 3', 'LEVEL 3')], default='NEW SELLER', max_length=120, null=True),
        ),
    ]
