# Generated by Django 3.2.6 on 2021-08-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_alter_extendeduser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LATE', 'LATE'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=200),
        ),
    ]
