# Generated by Django 3.2.6 on 2021-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_secondaryslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='extra_images',
        ),
        migrations.AddField(
            model_name='offer',
            name='extra_images',
            field=models.ManyToManyField(to='mainApp.ExtraImage'),
        ),
    ]
