# Generated by Django 3.2.6 on 2021-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_auto_20210825_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='images/'),
        ),
    ]
