# Generated by Django 3.2.6 on 2021-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_alter_extendeduser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_cancel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='on_review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
