# Generated by Django 3.2.6 on 2021-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0047_auto_20210825_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LATE', 'LATE'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('ON REVIEW', 'ON REVIEW')], default='ACTIVE', max_length=200),
        ),
    ]
