# Generated by Django 3.2.6 on 2021-08-26 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0048_alter_checkout_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtendedUser',
            new_name='SellerAccount',
        ),
    ]
