# Generated by Django 3.2.6 on 2021-08-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_rename_extendeduser_selleraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LATE', 'LATE'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('ON REVIEW', 'ON REVIEW')], default='ACTIVE', max_length=200),
        ),
    ]
