# Generated by Django 3.2.6 on 2021-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0050_alter_checkout_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
