# Generated by Django 3.2.6 on 2021-08-27 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0051_alter_selleraccount_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='created_at',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
