# Generated by Django 3.2.6 on 2021-08-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0052_selleraccount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
