# Generated by Django 3.2.6 on 2021-08-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_alter_selleraccount_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='created_at',
        ),
    ]
