# Generated by Django 3.2.6 on 2021-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0055_selleraccount_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='seo_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
