# Generated by Django 3.2.6 on 2021-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_offer_seo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
