# Generated by Django 3.2.6 on 2021-08-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0057_auto_20210827_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_responsive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision', to='mainApp.revision'),
        ),
    ]
