# Generated by Django 3.2.6 on 2021-08-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0058_auto_20210827_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='num_of_pages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_pages', to='mainApp.numberofpage'),
        ),
    ]
