# Generated by Django 3.2.6 on 2021-08-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0059_auto_20210827_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_responsive',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='num_of_pages',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='revision',
        ),
        migrations.AddField(
            model_name='package',
            name='is_responsive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='num_of_pages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_pages', to='mainApp.numberofpage'),
        ),
        migrations.AddField(
            model_name='package',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision', to='mainApp.revision'),
        ),
    ]
