# Generated by Django 3.2.6 on 2021-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0060_auto_20210827_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfPlugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='is_compitable',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='setup_payment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_deploy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='supported_formats',
            field=models.ManyToManyField(null=True, to='mainApp.FileFormats'),
        ),
    ]
