# Generated by Django 3.2.6 on 2021-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0062_auto_20210827_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_3dmockup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_campaign_optimization',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_high_res',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_transcription',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_translated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='management_duration',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='max_data',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='provide_excel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='provide_pdf',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='provide_vector',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='video_length',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_add_logo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_embedded_sub',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_sourcefile',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_srt_logo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
