# Generated by Django 3.2.6 on 2021-08-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0064_auto_20210827_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='is_responsive',
            new_name='is_responsive_basic',
        ),
        migrations.AddField(
            model_name='package',
            name='is_responsive_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_responsive_standard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
