# Generated by Django 3.2.6 on 2021-08-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0066_auto_20210831_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='is_high_res',
            new_name='is_high_res_for_basic',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='will_sourcefile',
            new_name='is_high_res_for_premium',
        ),
        migrations.AddField(
            model_name='package',
            name='is_high_res_for_standard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_sourcefile_for_basic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_sourcefile_for_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='will_sourcefile_for_standard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
