# Generated by Django 3.2.6 on 2021-08-31 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0067_auto_20210831_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='revision_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_basic', to='mainApp.revision'),
        ),
        migrations.AlterField(
            model_name='package',
            name='revision_premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_premium', to='mainApp.revision'),
        ),
        migrations.AlterField(
            model_name='package',
            name='revision_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_standard', to='mainApp.revision'),
        ),
    ]
