# Generated by Django 3.2.6 on 2021-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0068_auto_20210831_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='document',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
